# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Murmur' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.6.0'
  pod 'FirebaseCore', '9.0'
  pod 'FirebaseAuth', '9.0'
  pod 'FirebaseFirestore', '9.0'
  pod 'FirebaseStorage', '9.0'
  pod 'FirebaseFirestoreSwift', '9.0'
  pod 'FirebaseDatabase', '9.0'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher', '~> 7.0'
  pod 'lottie-ios'
  pod 'Toast-Swift', '~> 5.0.1'

  # Pods for Murmur

end
