# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Murmur' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  # Pods for Murmur

end
